language: node_js
dist: trusty
node_js:
  - 6.1
sudo: required
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - google-chrome --version
install:
  - npm install
  - npm install codecov
script:
  - npm run ng test -- --single-run=true --browsers Chrome --code-coverage
  - ./node_modules/codecov/bin/codecov
  - npm run e2e
  - npm run lint
  - npm run build -- --prod
  - npm run package
before_deploy:
  - cp -R dist aot && cd aot
deploy:
  - provider: s3
    access_key_id:
      secure: QDVJJQidCg1CHA7hsqK4zDNQ99ZZ7JcjoZbeFVzQrVW+qdJv/q4DBGzzyvut/trCsPiJ31eKVu5L853Uq6jjb6802h96fKTxgyn0nFbgZiK41LhZK4pYf7jX8MG0uiHVd+l0NCb1RYGNOamztYjI/bjznM+xaJScLonshOX2z0LQh4rOJbfBc6QCBhhSY6aOA32mcW67WnhKaF4u60mAM+l21gHNbo28/rYG/mwx1zWPrihJUz12C9nvMnFRkNcV+yp5fWPygv3oEpalRpo0scz5EYJyEXPodpFTfG4ktvcnx93MEmk3N/5EjX0lTWVGi86u6UsRTlkZ4Ai8nksPEK6PKZFk1LSpd8pMVbtswA8Kg3wu2sjaNnxdP8DGKs0hHnqaItLFwYJHlmfu4rEpqgM52vv29hWf1TZtpV84gNdqHFEQvhZVVRD5FbjgAGWYOgbmiTXCyBWDDX/LEOKjowI0hpRsfpJFPkZG+ryOVuOYWZmdo8xyzjRfhBnCU/uj8seyPQo7B7Ep6wwaP81NENEktMsVb5k/d3uG6XoFNEQEXNzyiUWzlhWwyaGboc4zg5wFmSRHwmHIDZRVxisig+VXTsB/rFzFw3sm1ZzTzArxWVhHZle6gw4k0Q8ZxiWYSXRBh0cEmmMHEH0pwTp2Ux2QsurIcyjWAMpVvrfAaTs=
    secret_access_key:
      secure: HktiS/tHorMz/svkPKbRurE3loF+Vxf53AIKXQSQQHglfo+agnp02/RYFKNULZs45vtA1Fp34fiACxvv/P2PArXYWQxg6znjWvtuIjxN0iYurB1zYuzZq60q+z6iZcbPGbowSvH0tKZZCRtzo1bmXeswIuwjhhSIvM0OvUwSYUtVWVudKJF0B8836EtXUZ2Dc5MtBN3W5/e6Nm2ILEHZ5XgJ/ZOqkkyCsaTa1H+4FdwlWLJpHof5fVm0hdjrBWHqNDCBzz46fMSIJfhX6Tw+TPqX2EPn8KRChhjBbAUjkiwOhXBI92y0JkxWzNmn0x+VlQrskih2ATQccWv3hpjUbrDIVcbChFJ8EGKlfRRUkFFC0KOEkUSXs84TLo0ifXKanYyvviTSRvp/pmsbTknbEw0FVsTQ1icaq5HEjEUT/qel6jJQH1lG14nin18klCHU907EMWANlB/9f+JlBRWH804dr6inqxvH+GEnNHjSy2VTFJfeVtBu+fP+JuDb0hZfZ6f/OS+mZ86lFVpfto3cdHmvWOubCwBmyRCT866Dj6SnBgyfxTDH5FNRfEjFhTrU9CdAfYKnVRrwuoNa1j7zRD3vGmmrNeQ1a3wLFlfD0oXyX/T+aUFErQLV6VhC8Ij3Zt+4y9BYwKsPd0JavmrDfgam+k0O6QLK1y+/AGdiGVI=
    bucket: poc.styleguide.online
    skip_cleanup: true
    local-dir: dist
    acl: public_read
    on:
      branch: master
  - provider: npm
    email: arranbartish@hotmail.com
    api_key:
      secure: foEiZeaPwxZ7aWJxvmDwbrXFgy7e29SRfrgp55xYwqfiVbhk9UOO+1IDBfJMJXMfreSyAFwodVOjvjEzNJX/rvJ1AeTAfW67UEh3+3fNPDQYIrvQRbi3HYCzDOrZwNg1vAGg68qmOX1IQJLJnaLa+Zkkfj0zAzbaNvKpssHT6ZEUf1Kly0VQ7q6K24pCbGmwQxLd874nKL2djPsZepKVoUmaki1CKAI0WyA7iHbUWZRC69Be6AjA9gyAlDSIGm8Nzb3ccR9sTahUJJ5TF7OAkbmy39JIlxjxPabGZNnfMos7FVs3xYRC9Yj50C7iF6NPnRtJ3r3WrdVhGsP6UshDS5BqhBpAd+H4BjsDfuqJE38jKJ1Ndl43am7x0gD7S0Bm8Ck9MIxNekWIKvJbkz6TJLVhlzDgSFxG7lzsde96BjchLqJk9ExDfsoveujywPdNk0JXjOXFo6C55kWsxFG/U+eiKT60+eXlXCVKnJKDfssyRns0pOt2F/KBXbhhgQTeNyeeArby7KVy4lTzCRBnG9a3GvFtUMs/XhjnAJTy0UoJIltoi6JQCpYvdUfHXlFfYWmhW65iFVQtYdpd1X1gqGlJNe3td8RgsZ+byKoVfn6Gb6YonZbRu01mz05mXYZpp3NZ7V4I0TmqKql+2X4OcJapWjyPGr5fy/seLSXpuI0=
    skip_cleanup: true
    local-dir: aot
    on:
      tags: true
